import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="bg-blue-700 text-white p-16 text-center">
        Welcome to Next.js with Recoil and JEST and React Testing Library!
      </h1>
    </div>
  );
};

export default Home;
